### ISSUE TITLE
Create Homepage | RawGit will be shut off. Find a different way to get this homepage template

### ISSUE THREAD

**Issue by danverde** [byuitechops/create-homepage#19]
https://github.com/byuitechops/create-homepage/blob/550139c8a0ba6c98f3381a51ad3246460b0600fa/main.js#L55

**Comment by Wilson-Cal** [comment]
Fixed in commit [0e39d6a](https://github.com/byuitechops/create-homepage/commit/0e39d6a8da85b1b319073f1ac2639f7cbf949551)
