### ISSUE TITLE
Link to templates by name?

### ISSUE THREAD

**Issue by danverde** [byuitechops/create-homepage#23]
I know we just updated this to use ID's, but it recently broke b/c someone deleted the page & created a new one with the same name (but a new ID). It might actually be safer to use the name.

**Comment by Wilson-Cal** [comment]
@danverde Could we do both?

**Comment by danverde** [comment]
@Wilson-Cal That's not a bad idea. Maybe search by ID, but if the id no longer exists search by name?

**Comment by danverde** [comment]
@Wilson-Cal can I get you to implement this for me? I had another homepage link break this morning. the link to basic details is broken

**Comment by danverde** [comment]
actually it looks like we'll need to talk about this with the FTC & CCD. The page has been renamed or completely deleted

**Comment by Wilson-Cal** [comment]
Added the ability to search first by ID, then Name in pull request #26
