### ISSUE TITLE
"Lesson" buttons don't show up when creating homepage with this child module

### ISSUE THREAD

**Issue by zachintosh** [byuitechops/create-homepage#3]
"Lesson" buttons don't show up when creating homepage with this child module

**Comment by zachintosh** [comment]
Lesson buttons and additional resources do not work on import. Lesson buttons don't show up. Additional resources is incorrectly linked.

**Comment by zachintosh** [comment]
Additional Resources is probably not linking because student resources hasn't been created yet.

**Comment by danverde** [comment]
This is an issue created by the BYUI theme JS page, not the child module

**Comment by zachintosh** [comment]
Fixed - issue was in the template's js.
